### ISSUE TITLE
Allow any type of kubernetes resources on template data

### ISSUE THREAD

**Issue by eryalito** [eryalito/kubensync-operator#63]
# Description
Currently secrets and configmaps contents can be injected into the template using the `spec.template.data` key:

```yaml
spec:
    template:
        data:
        - name: pull_secret
          type: Secret
          ref:
            name: my-pull-secret
            namespace: default
```
This would retrieve the `my-pull-secret` from the `default` namespace and inject it into the go template values as `.Data.pull_secret`. This already parses the `.data` fields of the secret/cm and add the key-values directly. 

The ideas here is to extend this data behavior to generic kubernetes resoruces. In that way the `ref` would be the resource group, apiVersion, kind, resource name and namespace (if namespaced). The operator would retrieve that resource and expose it directly as the whole resoruce under `.Data.<name>` so for example if it was a Deployment and want to get the name it would be `.Data.my_resource.metadata.name`
